[project]
name = "sonnet"
revision = "1.0"

[profiles.development]
SONNET_OIDCC_CLIENT_ID = { required = true }
SONNET_OIDCC_CLIENT_SECRET = { required = true }
SONNET_OIDCC_ISSUER = { required = true }

[profiles.ci]
