name: Release

on:
  release:
    types: [published]

jobs:
  build:
    uses: docker/github-builder/.github/workflows/build.yml@5f637c833aa76bc99372a1dc9a6f8bcd8056fb85 # v1
    permissions:
      contents: read
      id-token: write
      packages: write
    with:
      distribute: true
      output: image
      push: true
      platforms: linux/amd64,linux/arm64
      cache: true
      cache-mode: max
      file: "Containerfile"
      meta-images: |
        quay.io/drangon/sonnet
        ghcr.io/bepoesied/sonnet
      meta-tags: |
        type=semver,pattern=v{{version}}
        type=semver,pattern=v{{major}}.{{minor}}
        type=raw,value=latest
    secrets:
      registry-auths: |
        - registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
        - registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
